### ISSUE TITLE
HTTPS connection - Minor bug

### ISSUE THREAD

**Issue by ivanguasch** [viewflow/django-material#121]
Minor bug in **django-material/material/static/material/css/robotofix.css** when django-material is used with an https connection. Maybe, you should change:
**"src: url(http://themes.googleusercontent.com/static/fonts/roboto/v10..."** 
by
**"src: url(//themes.googleusercontent.com/static/fonts/roboto/v10..."**

Great job.

**Comment by kmmbvnr** [comment]
Generally, i'm thinking about to drop that hack, since materialze.css now have woff2 roboto font.

If you on windows, could you please check http://materializecss.com/ website?

Do you have a font rendering issues like that:
http://stackoverflow.com/questions/31011278/roboto-from-materializecss-weird-font-rendering-in-chrome-firefox-ok-with-ie
