### ISSUE TITLE
Admin dashboard with single app layout problem under FF

### ISSUE THREAD

**Issue by blindpenguin** [viewflow/django-material#220]
Hi,

i just installed it in a new Django 1.10 project. In Chrome it looks just fine, but in Firefox those squares look kinda broken. After hovering or clicking on one of those squares, they disappear completely. 

Firefox: 50.1.0
OS: Win 10 Pro

![brokenadmin](https://cloud.githubusercontent.com/assets/4688741/21751640/c288a978-d5ca-11e6-9a66-9dbbe1f00eae.png)

**Comment by kmmbvnr** [comment]
Confirmed, That happens even under FF 53, but when the only 1 app listed in the admin dashboard.

![dashboard](https://cloud.githubusercontent.com/assets/282529/21757217/8e580b5e-d655-11e6-8588-77cd187cb693.png)

![dashboard2](https://cloud.githubusercontent.com/assets/282529/21757227/c5ae1b02-d655-11e6-918d-187a0bc248a1.png)

Since, the problem is pretty minor and not going to happens in prod, I'm not going to fix it, but pull requests are welcome anyway :)
