### ISSUE TITLE
Admin file input link

### ISSUE THREAD

**Issue by cyberbudy** [viewflow/django-material#288]
By default django admin file input has a link to open saved image.
![image](https://user-images.githubusercontent.com/10235359/27128934-2e8334b8-5109-11e7-992d-bcacb7cebead.png)
But it seems that material admin does not display that. It would be a very handy to implement some kind of help_text link with file url.

**Comment by preusx** [comment]
What about a pull request with this feature? Would you apply it?

**Comment by kmmbvnr** [comment]
Generally, I don't like an idea to modify `help_text` This would definitely someone others unhappy.

Increasing control height with the additional line also not looks good, in case if a file field would be combined with another field in a row.

So probably the best way is to make file name clickable and styled as a link. But this would require extra work with css styling and js, since `<input>` tag can't be used in that case.

http://forms.viewflow.io/demo/widget/admin/adminfilewidget/

**Comment by kmmbvnr** [comment]
Another idea - is to put small download icon on the right of the text field. This probably would be a bit simpler

![material design for django forms and admin](https://user-images.githubusercontent.com/282529/27169056-05b96040-51ca-11e7-9383-0eb9e069189e.png)
