### ISSUE TITLE
Unable to override login.html template

### ISSUE THREAD

**Issue by opw0011** [viewflow/django-material#305]
I followed the guide here:
http://docs.viewflow.io/admin_customization.html#template-blocks

I created a file './templates/admin/login.html' and tried to override the {% block main %} {% endblock %}, but nothing had changed. Is there any example on how to modify it?

**Comment by SpikingNeurons** [comment]
Same problem here. I even tried './templates/admin/<app name>/login.html'  as per django documentation. But that too did not work for me

**Comment by SpikingNeurons** [comment]
Oops that is specific to Django

**Comment by kmmbvnr** [comment]
Templates and Static files are completely different things.

The valid instructions still here - http://docs.viewflow.io/admin_customization.html#template-blocks

YMMV depends on project layout. You just have to ensure that TEMPLATE['DIRS'] pointed to the right directory.

**Comment by SpikingNeurons** [comment]
@kmmbvnr I am bit new to Django.
I was trying to override {% block userphoto %}. I was able to override it, but the photo did not appear. 
I used `django-avatar` for the same.
Then I realized that photos are stored in MEDIA_URL which cannot be loaded statically.

Sorry my bad. The above code snippet is in relation to loading media content as static file, so that photo can appear.
