### ISSUE TITLE
Decimal field issues

### ISSUE THREAD

**Issue by fbrau** [viewflow/django-material#72]
the field is
`
porcentaje = models.DecimalField(max_digits=4, decimal_places=2,
                   blank=True, null=True,
                   help_text='Porcentaje de afiliacion')
`

Template with django default templatetag {{form.as_table}} produces the html
`
<input type="number" value="1.10" step="0.01" name="porcentaje" id="id_porcentaje">
`
(it actually renders as 1,1 in the browser, btw...)

Changing the templatetag with 
`          {% form form=form %}{% endform %}
`
produces the html
`<input type="number" value="1,10" id="id_porcentaje" step="0.01" name="porcentaje">`
which firefox and midori browsers dont draw at all (firefox doesnt even show a warning or something,
it just silently skips drawing the value.

My settings.py localization values are
`LANGUAGE_CODE = 'es'

TIME_ZONE = 'localtime'

USE_I18N = True

USE_L10N = True

USE_TZ = False
`

I dont know if this is a bug the material django app, in the materializecss framework
or a bad configuration.

**Comment by kmmbvnr** [comment]
http://forms.viewflow.io/demo/widget/decimal/

**Comment by AliLozano** [comment]
I have the same issue, the problem is when it uses USE_L10N = True, the html generated is 
`<input` type="number" value="1,10" step="0.01" name="porcentaje" id="id_porcentaje"> 

The value is internationalized with comma, and browsers don't recognize it and leave the field in blank. 

The solution?, could be don't use internationalization with the value.

**Comment by kmmbvnr** [comment]
lol. i'm working on it right now
