### ISSUE TITLE
RadioSelectInput issues

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/django-material#88]
http://forms.viewflow.io/demo/widget/radioselect/

Values is not selected after form submit

**Comment by diegocmsantos** [comment]
On submit {% if value == bound_field.value %}checked{% endif %} fails because bound_field.value is '2' and it needs to be a integer.

My fixing approach was:
at django_radioselect.html
`{% if value in bound_field.value|str_to_int %}checked{% endif %}`

at material_form_internal.py
```python
@register.filter
def str_to_int(bound_field_list):
    if not isinstance(bound_field_list, list):
        bound_field_list = [bound_field_list]
    return list(map(int, bound_field_list))
```

If you approve I can send you a PR.

Regards.

**Comment by kmmbvnr** [comment]
@diegocmsantos  Values can't be coerced to int b/c RadioInput choices could be non-int values, ex with [ModelChoiceField with to_field_name](https://docs.djangoproject.com/es/1.9/ref/forms/fields/#django.forms.ModelChoiceField.to_field_name)

**Comment by diegocmsantos** [comment]
Nice.
I'm kind novice in django.
But I hope you don't mind if I keep trying to help this project.

**Comment by kmmbvnr** [comment]
Sure! Any help is appreciated.

Would you like to start to work on some small issues?
