### ISSUE TITLE
CheckboxSelectMultiple issues

### ISSUE THREAD

**Issue by kmmbvnr** [viewflow/django-material#89]
http://forms.viewflow.io/demo/widget/checkboxmultiple/

values are not selected after submit

**Comment by diegocmsantos** [comment]
On submit {% if value in bound_field.value %}checked{% endif %} fails because bound_field.value is ['2', '3'] and it needs to be a integer list.

My fixing approach was:
at django_checkboxselectmultiple.html
`{% if value in bound_field.value|str_to_int %}checked{% endif %}`

at material_form_internal.py
```python
@register.filter
def str_to_int(bound_field_list):
    return list(map(int, bound_field_list))
```

If you approve I can send you a PR.

Regards.
