### ISSUE TITLE
How to Enable/Disable material select

### ISSUE THREAD

**Issue by manuelvcr** [viewflow/django-material#94]
Hi, I have built a form that contains 4 select.

When I select a value in the first select, I have a script that enable or disable the others, but the selects don't change and keep in their current state.

I have included some traces in the javascript code and I can see that the code is executing correctly, but the selects in the form don't change.

I have also tested with radiobuttons, trying to enable another fields according at the value selected, but it doesn't work.

**Comment by kmmbvnr** [comment]
This issue is not related to django-material library. [MaterializeCSS](http://materializecss.com/) substitutes selects to several html tags. Probably triggering `$('#id_select').material_select();` will solve your issue, if not, it's a good question for stackoverflow.

* http://stackoverflow.com/questions/29132125/how-to-dynamically-modify-select-in-materialize-css-framework
